/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.InterfazBase;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author kp728
 */
public class AgregarVuelo extends javax.swing.JFrame {

    /**
     * Creates new form AgregarVuelo
     */
    public AgregarVuelo() {
        initComponents();
        tblAviones.setModel(InterfazBase.extraerAviones());
        
        SpinnerDateModel modelo = new SpinnerDateModel();
        spHsalida.setModel(modelo);
        JSpinner.DateEditor editor = new JSpinner.DateEditor(spHsalida, "HH:mm:ss");
        spHsalida.setEditor(editor);
        
        spHllegada.setModel(modelo);
        JSpinner.DateEditor editor2 = new JSpinner.DateEditor(spHllegada, "HH:mm:ss");
        spHllegada.setEditor(editor2);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtDestino = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dateSalida = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        dateLlegada = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAviones = new javax.swing.JTable();
        spHllegada = new javax.swing.JSpinner();
        spHsalida = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setText("Hora de salida: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 153, -1, -1));

        btnRegistrar.setBackground(new java.awt.Color(106, 139, 252));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, -1));

        txtDestino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        txtDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDestinoKeyReleased(evt);
            }
        });
        jPanel1.add(txtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 300, 30));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setText("Lugar de destino:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        txtOrigen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOrigen.setText("Oaxaca");
        txtOrigen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        txtOrigen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOrigenKeyReleased(evt);
            }
        });
        jPanel1.add(txtOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 300, 30));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setText("Lugar de origen:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel1.setBackground(new java.awt.Color(50, 50, 188));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de vuelos");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 44));

        dateSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        jPanel1.add(dateSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 111, 300, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setText("Fecha de Salida:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 82, -1, -1));

        dateLlegada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        jPanel1.add(dateLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 111, 300, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("Fecha de llegada:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 82, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setText("Hora de Llegada: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 153, -1, -1));

        tblAviones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAviones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblAviones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 671, 130));
        jPanel1.add(spHllegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 300, -1));
        jPanel1.add(spHsalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 188, 300, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 780, 540));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/multiplication_3032283.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 25, 25));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black-backgrounds-7.jpg"))); // NOI18N
        lblFondo.setPreferredSize(new java.awt.Dimension(1200, 780));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -120, 1000, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if(!(dateSalida.getDate().equals(dateLlegada.getDate()))  && dateSalida.getDate().before(dateLlegada.getDate())){
            if(!(txtOrigen.getText().equals(txtDestino.getText()))){
                
                    Date date = (Date) spHsalida.getValue();
                    DateTimeFormatter formato = DateTimeFormatter.ofPattern("HH:mm:ss");
                    LocalTime Hsalida = LocalTime.parse(new SimpleDateFormat("HH:mm:ss").format(date), formato);
                    
                    Date date2 = (Date) spHllegada.getValue();
                    LocalTime Hllegada = LocalTime.parse(new SimpleDateFormat("HH:mm:ss").format(date2), formato);
                
                if(InterfazBase.registarVuelo(dateSalida.getDate(), Hsalida, dateLlegada.getDate() , Hllegada, txtOrigen.getText(), txtDestino.getText(), InterfazBase.obtenerIdAvion2(tblAviones))){
                   JOptionPane.showMessageDialog(null, "Registro exitoso");
                   InterfazBase.actualizarAvion(InterfazBase.obtenerIdAvion2(tblAviones), false);
                   VistaAdministrador.tblVuelos.setModel(InterfazBase.extraerViajes());
                   dispose();
                }
            } 
            else{
            JOptionPane.showMessageDialog(null, "El origen y destino no pueden ser iguales");
            }
        } else{
            JOptionPane.showMessageDialog(null, "Formato de fechas no valido");
        }
        
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtOrigenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrigenKeyReleased
        if(!Character.isLetter(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtOrigenKeyReleased

    private void txtDestinoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDestinoKeyReleased
        if(!Character.isLetter(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtDestinoKeyReleased

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarVuelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private com.toedter.calendar.JDateChooser dateLlegada;
    private com.toedter.calendar.JDateChooser dateSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JSpinner spHllegada;
    private javax.swing.JSpinner spHsalida;
    private javax.swing.JTable tblAviones;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
