/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Correo;
import Controlador.InterfazBase;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author kp728
 */
public class asientosAvion extends javax.swing.JFrame {

    /**
     * Creates new form asientosAvion
     */
    boolean[] asientosBase = {false, false, false, false, false, false, false, false, false, false};
    static int idavion = 0, idC = 0, idvuelo = 0;
    JLabel[] asientosLabels;
    int asiento = 0;
    public asientosAvion(int id_avion, int id_cliente, int id_vuelo) {
        initComponents();
        idavion = id_avion;
        idC = id_cliente;
        idvuelo = id_vuelo;
        lblAsientoC.setBackground(Color.DARK_GRAY);
        asientosLabels = new JLabel[]{lblAsiento1, lblAsiento2, lblAsiento3, lblAsiento4, lblAsiento5, lblAsiento6, lblAsiento7, lblAsiento8, lblAsiento9, lblAsiento10};
        asientosBase = InterfazBase.estadoAsientos(idavion);
        mostrarAsientos();
        panelOpaco1.setOpacity(0.5f);
    }
    
    
    private void desmarcarAsientos(int asientoSeleccionado) {
        for (int i = 0; i < asientosBase.length; i++) {
            if (i != asientoSeleccionado) {
                if(!asientosBase[i]){
                    asientosBase[i] = false;
                    asientosLabels[i].setBackground(Color.WHITE);
                }
            }
        }
    }
    
    public void mostrarAsientos() {
        if (asientosBase == null || asientosLabels == null) {
            throw new NullPointerException("Los arrays de asientos o labels son null.");
        }
        InterfazBase.bloquearAsiento(asientosBase, asientosLabels);
    }
    
    private int obtenerAsientoSeleccionado() {
        for (int i = 0; i < asientosLabels.length; i++) {
            if (asientosLabels[i].getBackground().equals(Color.DARK_GRAY)) {
                return i + 1; 
            }
        }
        return -1; 
    }
    
    public void manejarClickAsiento(int index, JLabel lblAsiento) {
        if (!asientosBase[index]) {
            asiento = index + 1;
            asientosBase[index] = true;
            lblAsiento.setBackground(Color.DARK_GRAY);
            desmarcarAsientos(index);
        } else {
            JOptionPane.showMessageDialog(null, "Elija un asiento disponible");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOpaco1 = new elementos.panelOpaco();
        lblAsientoDO1 = new javax.swing.JLabel();
        lblAsientoC = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        lblAsiento1 = new javax.swing.JLabel();
        lblAsiento2 = new javax.swing.JLabel();
        lblAsiento3 = new javax.swing.JLabel();
        lblAsiento4 = new javax.swing.JLabel();
        lblAsiento5 = new javax.swing.JLabel();
        lblAsiento6 = new javax.swing.JLabel();
        lblAsiento7 = new javax.swing.JLabel();
        lblAsiento8 = new javax.swing.JLabel();
        lblAsiento9 = new javax.swing.JLabel();
        lblAsiento10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelOpaco1.setBackground(new java.awt.Color(255, 255, 255));
        panelOpaco1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAsientoDO1.setBackground(new java.awt.Color(255, 255, 255));
        lblAsientoDO1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsientoDO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seat_7474361.png"))); // NOI18N
        lblAsientoDO1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        lblAsientoDO1.setOpaque(true);
        panelOpaco1.add(lblAsientoDO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 70, 70));

        lblAsientoC.setBackground(new java.awt.Color(255, 255, 255));
        lblAsientoC.setForeground(new java.awt.Color(255, 255, 255));
        lblAsientoC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsientoC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seat_7474361.png"))); // NOI18N
        lblAsientoC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        lblAsientoC.setOpaque(true);
        panelOpaco1.add(lblAsientoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 70, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("OCUPADO");
        panelOpaco1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DISPONIBLE");
        panelOpaco1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setOpaque(true);
        panelOpaco1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 470, 90));

        btnReservar.setBackground(new java.awt.Color(0, 153, 153));
        btnReservar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReservar.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });
        panelOpaco1.add(btnReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, -1, -1));

        lblAsiento1.setBackground(new java.awt.Color(255, 255, 255));
        lblAsiento1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsiento1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seat_7474361.png"))); // NOI18N
        lblAsiento1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAsiento1.setOpaque(true);
        lblAsiento1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAsiento1MouseClicked(evt);
            }
        });
        panelOpaco1.add(lblAsiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 50, 60));

        lblAsiento2.setBackground(new java.awt.Color(255, 255, 255));
        lblAsiento2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsiento2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seat_7474361.png"))); // NOI18N
        lblAsiento2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAsiento2.setOpaque(true);
        lblAsiento2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAsiento2MouseClicked(evt);
            }
        });
        panelOpaco1.add(lblAsiento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 50, 60));

        lblAsiento3.setBackground(new java.awt.Color(255, 255, 255));
        lblAsiento3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsiento3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seat_7474361.png"))); // NOI18N
        lblAsiento3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAsiento3.setOpaque(true);
        lblAsiento3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAsiento3MouseClicked(evt);
            }
        });
        panelOpaco1.add(lblAsiento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 50, 60));

        lblAsiento4.setBackground(new java.awt.Color(255, 255, 255));
        lblAsiento4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsiento4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seat_7474361.png"))); // NOI18N
        lblAsiento4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAsiento4.setOpaque(true);
        lblAsiento4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAsiento4MouseClicked(evt);
            }
        });
        panelOpaco1.add(lblAsiento4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 50, 60));

        lblAsiento5.setBackground(new java.awt.Color(255, 255, 255));
        lblAsiento5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsiento5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seat_7474361.png"))); // NOI18N
        lblAsiento5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAsiento5.setOpaque(true);
        lblAsiento5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAsiento5MouseClicked(evt);
            }
        });
        panelOpaco1.add(lblAsiento5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 50, 60));

        lblAsiento6.setBackground(new java.awt.Color(255, 255, 255));
        lblAsiento6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsiento6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seat_7474361.png"))); // NOI18N
        lblAsiento6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAsiento6.setOpaque(true);
        lblAsiento6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAsiento6MouseClicked(evt);
            }
        });
        panelOpaco1.add(lblAsiento6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 50, 60));

        lblAsiento7.setBackground(new java.awt.Color(255, 255, 255));
        lblAsiento7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsiento7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seat_7474361.png"))); // NOI18N
        lblAsiento7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAsiento7.setOpaque(true);
        lblAsiento7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAsiento7MouseClicked(evt);
            }
        });
        panelOpaco1.add(lblAsiento7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 50, 60));

        lblAsiento8.setBackground(new java.awt.Color(255, 255, 255));
        lblAsiento8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsiento8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seat_7474361.png"))); // NOI18N
        lblAsiento8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAsiento8.setOpaque(true);
        lblAsiento8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAsiento8MouseClicked(evt);
            }
        });
        panelOpaco1.add(lblAsiento8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 50, 60));

        lblAsiento9.setBackground(new java.awt.Color(255, 255, 255));
        lblAsiento9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsiento9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seat_7474361.png"))); // NOI18N
        lblAsiento9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAsiento9.setOpaque(true);
        lblAsiento9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAsiento9MouseClicked(evt);
            }
        });
        panelOpaco1.add(lblAsiento9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 50, 60));

        lblAsiento10.setBackground(new java.awt.Color(255, 255, 255));
        lblAsiento10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsiento10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seat_7474361.png"))); // NOI18N
        lblAsiento10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAsiento10.setOpaque(true);
        lblAsiento10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAsiento10MouseClicked(evt);
            }
        });
        panelOpaco1.add(lblAsiento10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 50, 60));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2.jpg"))); // NOI18N
        panelOpaco1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 530, 200));

        getContentPane().add(panelOpaco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 800, 600));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/multiplication_3032283.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 20, 25, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/img1.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1200, 780));
        jLabel1.setPreferredSize(new java.awt.Dimension(1200, 780));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        int asientoSeleccionado = obtenerAsientoSeleccionado(); 
        boolean asientoActualizado = InterfazBase.actualizarAsiento(idavion, asientoSeleccionado, true);
        boolean reservaRegistrada = InterfazBase.registrarReserva(idC, idvuelo);
        if (asientoSeleccionado != -1 && asientoActualizado && reservaRegistrada) {
            JOptionPane.showMessageDialog(null, "Reserva exitosa");
            VistaVuelos.tblViajes.setModel(InterfazBase.extraerViajes());
            Correo.enviarPDF(InterfazBase.obtenerCorreoCliente(idC),idvuelo);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Error en la reserva");
        }
    }//GEN-LAST:event_btnReservarActionPerformed

    private void lblAsiento1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsiento1MouseClicked
        manejarClickAsiento(0, lblAsiento1);
    }//GEN-LAST:event_lblAsiento1MouseClicked

    private void lblAsiento2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsiento2MouseClicked
        manejarClickAsiento(1, lblAsiento2);
    }//GEN-LAST:event_lblAsiento2MouseClicked

    private void lblAsiento3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsiento3MouseClicked
        manejarClickAsiento(2, lblAsiento3);
    }//GEN-LAST:event_lblAsiento3MouseClicked

    private void lblAsiento4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsiento4MouseClicked
        manejarClickAsiento(3, lblAsiento4);
    }//GEN-LAST:event_lblAsiento4MouseClicked

    private void lblAsiento5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsiento5MouseClicked
        manejarClickAsiento(4, lblAsiento5);
    }//GEN-LAST:event_lblAsiento5MouseClicked

    private void lblAsiento6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsiento6MouseClicked
        manejarClickAsiento(5, lblAsiento6);
    }//GEN-LAST:event_lblAsiento6MouseClicked

    private void lblAsiento7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsiento7MouseClicked
        manejarClickAsiento(6, lblAsiento7);
    }//GEN-LAST:event_lblAsiento7MouseClicked

    private void lblAsiento8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsiento8MouseClicked
        manejarClickAsiento(7, lblAsiento8);
    }//GEN-LAST:event_lblAsiento8MouseClicked

    private void lblAsiento9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsiento9MouseClicked
        manejarClickAsiento(8, lblAsiento9);
    }//GEN-LAST:event_lblAsiento9MouseClicked

    private void lblAsiento10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsiento10MouseClicked
        manejarClickAsiento(9, lblAsiento10);
    }//GEN-LAST:event_lblAsiento10MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(asientosAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(asientosAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(asientosAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(asientosAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new asientosAvion(idavion,idC,idvuelo).setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReservar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblAsiento1;
    private javax.swing.JLabel lblAsiento10;
    private javax.swing.JLabel lblAsiento2;
    private javax.swing.JLabel lblAsiento3;
    private javax.swing.JLabel lblAsiento4;
    private javax.swing.JLabel lblAsiento5;
    private javax.swing.JLabel lblAsiento6;
    private javax.swing.JLabel lblAsiento7;
    private javax.swing.JLabel lblAsiento8;
    private javax.swing.JLabel lblAsiento9;
    private javax.swing.JLabel lblAsientoC;
    private javax.swing.JLabel lblAsientoDO1;
    private elementos.panelOpaco panelOpaco1;
    // End of variables declaration//GEN-END:variables
}
