/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Correo;
import Controlador.InterfazBase;
import javax.swing.JOptionPane;

/**
 *
 * @author kp728
 */
public class VistaVuelos extends javax.swing.JFrame {

    /**
     * Creates new form Vuelos
     */
    static int id_cliente;
    public VistaVuelos(int id) {
        initComponents();
        pnl1.setOpacity(0.5f);
        tblViajes.setModel(InterfazBase.extraerViajes());
        id_cliente = id;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViajes = new javax.swing.JTable();
        pnl1 = new elementos.panelOpaco();
        lblReservar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblReservaciones = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblViajes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblViajes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblViajes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 740, 550));

        pnl1.setBackground(new java.awt.Color(0, 0, 0));
        pnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReservar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReservar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReservarMouseClicked(evt);
            }
        });
        pnl1.add(lblReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/airplane_1023319.png"))); // NOI18N
        pnl1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 70));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Reservar");
        pnl1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, -1));

        lblReservaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReservaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReservacionesMouseClicked(evt);
            }
        });
        pnl1.add(lblReservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 90, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/booking_2460877.png"))); // NOI18N
        pnl1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 70));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Reservaciones");
        pnl1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 90, -1));

        lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });
        pnl1.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 90, 90));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eviction_1464167.png"))); // NOI18N
        pnl1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, 70));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Salir");
        pnl1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 90, -1));

        getContentPane().add(pnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 140, 720));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/img4.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblReservacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReservacionesMouseClicked
        new Reservaciones(id_cliente).setVisible(true);
    }//GEN-LAST:event_lblReservacionesMouseClicked

    private void lblReservarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReservarMouseClicked
        int avion = InterfazBase.obtenerIdAvion(tblViajes);
        int vuelo = InterfazBase.obtenerIdVuelo(tblViajes);
        if(avion != 0){
            new asientosAvion(avion,id_cliente,vuelo).setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Elija un avion antes de reservar");
        }
    }//GEN-LAST:event_lblReservarMouseClicked
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaVuelos(id_cliente).setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblReservaciones;
    private javax.swing.JLabel lblReservar;
    private javax.swing.JLabel lblSalir;
    private elementos.panelOpaco pnl1;
    public static javax.swing.JTable tblViajes;
    // End of variables declaration//GEN-END:variables
}
